export enum ROUTES {
  AUTH_PAGE = "/auth",
  AUTHORIZED_PAGE = "/",
  MAIN_PAGE = "/main",
  VACANCY_LIST_PAGE = "/vacancy-list",
  CATEGORY_PAGE = "/category",
  ACTIVITY_PAGE = "/activity",
  ACTIVITY_EDIT_PAGE = "edit",
  EVENT_PAGE = "/event",
  PEOPLES_PAGE = "/peoples",
  MESSAGE_PAGE = "/messages",
  MY_ACTIVITIES_PAGE = "/activities",
  PROFILE_PAGE = "/profile",
  VACANCY_PAGE = "/vacancy",
  CLAIMS_PAGE = "/claims",
}
